.\" Manpage for daisy-discoverd.
.TH man 8 "08 Oct 2014" "1.0" "daisy-discoverd man page"
.SH NAME
daisy-discoverd \- hardware discovery daemon for OpenStack Ironic.
.SH SYNOPSIS
daisy-discoverd CONFFILE
.SH DESCRIPTION
This command starts daisy-discoverd service, which starts and finishes
hardware discovery for nodes accessing PXE boot service (usually dnsmasq).
.SH OPTIONS
The daisy-discoverd does not take any options. However, you should supply
path to the configuration file.
.SH SEE ALSO
README page located at https://pypi.python.org/pypi/daisy-discoverd
provides some information about how to configure and use the service.
.SH BUGS
No known bugs.
.SH AUTHOR
Dmitry Tantsur (divius.inside@gmail.com)
