#!/bin/sh
yum install -y atk
yum install -y docutils
yum install -y fontawesome-fonts-web
yum install -y gd
yum install -y gdk-pixbuf2
yum install -y gettext-common-devel
yum install -y gettext-devel
yum install -y git
yum install -y graphite2
yum install -y graphviz
yum install -y gtk2
yum install -y harfbuzz
yum install -y hicolor-icon-theme
yum install -y intltool
yum install -y librsvg2
yum install -y libthai
yum install -y libtool
yum install -y libXaw
yum install -y libXcomposite
yum install -y libXcursor
yum install -y libXft
yum install -y libXi
yum install -y libXmu
yum install -y libXpm
yum install -y libXrandr
yum install -y pango
yum install -y perl-XML-Parser
yum install -y Pygments
yum install -y python-anyjson
yum install -y python-boto
yum install -y python-d2to1
yum install -y python-django-appconf
yum install -y python-django-compressor
yum install -y python-django-openstack-auth
yum install -y python-django-pyscss
yum install -y python-eventlet
yum install -y python-eventlet
yum install -y python-greenlet
yum install -y python-iso8601
yum install -y python-jinja2
yum install -y python-keystoneclient
yum install -y python-kombu
yum install -y python--0.9j
yum install -y python-lockfile
yum install -y python-migrate
yum install -y python-oslo-concurrency
yum install -y python-oslo-config
yum install -y python-oslo-i18n
yum install -y python-oslo-serialization
yum install -y python-oslo-sphinx
yum install -y python-oslo-utils
yum install -y python-pbr
yum install -y python-pint
yum install -y python-pygments
yum install -y python-routes
yum install -y python-scss
yum install -y python-six
yum install -y python-sphinx
yum install -y python-sqlalchemy
yum install -y python-sqlalchemy
yum install -y python-webob
yum install -y python-XStatic
yum install -y python-XStatic-Angular
yum install -y python-XStatic-Angular-Bootstrap
yum install -y python-XStatic-Angular-lrdragndrop
yum install -y python-XStatic-Angular-Mock
yum install -y python-XStatic-Bootstrap-Datepicker
yum install -y python-XStatic-Bootstrap-SCSS
yum install -y python-XStatic-D3
yum install -y python-XStatic-Font-Awesome
yum install -y python-XStatic-Hogan
yum install -y python-XStatic-Jasmine
yum install -y python-XStatic-jQuery
yum install -y python-XStatic-JQuery-Migrate
yum install -y python-XStatic-JQuery-quicksearch
yum install -y python-XStatic-JQuery-TableSorter
yum install -y python-XStatic-jquery-ui
yum install -y python-XStatic-JSEncrypt
yum install -y python-XStatic-Magic-Search
yum install -y python-XStatic-QUnit
yum install -y python-XStatic-Rickshaw
yum install -y python-XStatic-smart-table
yum install -y python-XStatic-Spin
yum install -y python-XStatic-termjs
