#!/bin/sh
yum -y install \
  coreutils \
  git \
  intltool \
  make \
  rpm \
  rpm-build \
  python-sphinx \
  python-XStatic-Angular \
  python-XStatic-Angular-Bootstrap \
  python-XStatic-Angular-lrdragndrop \
  python-XStatic-Angular-Mock \
  python-XStatic-Bootstrap-Datepicker \
  python-XStatic-Bootstrap-SCSS \
  python-XStatic-D3 \
  python-XStatic-Font-Awesome \
  python-XStatic-Hogan \
  python-XStatic-Jasmine \
  python-XStatic-jQuery \
  python-XStatic-JQuery-Migrate \
  python-XStatic-JQuery-quicksearch \
  python-XStatic-JQuery-TableSorter \
  python-XStatic-jquery-ui \
  python-XStatic-JSEncrypt \
  python-XStatic-Magic-Search \
  python-XStatic-QUnit \
  python-XStatic-Rickshaw \
  python-XStatic-smart-table \
  python-XStatic-Spin \
  python-XStatic-termjs \
  python2-openstackdocstheme \
  python2-oslo-messaging \
  python2-oslo-concurrency \
  python-devel \
  python-d2to1 \
  python-django-compressor \
  python-django-openstack-auth \
  python-django-pyscss \
  python-lesscpy \
  python-migrate \
  python-pint \
  python-routes \
  gcc \
  autoconf \
  automake \
  glibc-devel
